/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ConexionBD.ConexionUsuarios;
import Datos.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    public static Usuario USUARIO ;
    
    public Login() {
        initComponents();
        TxtContraseña.setText("");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        TxtContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonRegistrarce = new javax.swing.JButton();
        BotonIniciarSecion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 240, 40));

        TxtContraseña.setText("jPasswordField1");
        jPanel1.add(TxtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 250, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Correo Electronico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 210, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 140, -1));

        BotonRegistrarce.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonRegistrarce.setText("Registrarse");
        BotonRegistrarce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarceActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistrarce, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 120, 30));

        BotonIniciarSecion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotonIniciarSecion.setText("Iniciar Sesion");
        BotonIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSecionActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIniciarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Herramientas.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorreoActionPerformed

    private void BotonRegistrarceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarceActionPerformed
        this.dispose();
        RegistroUsuarios ventanaUsuarios = new RegistroUsuarios();
        ventanaUsuarios.setLocationRelativeTo(null);
        ventanaUsuarios.setVisible(true);
    }//GEN-LAST:event_BotonRegistrarceActionPerformed

    private boolean ValidarEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }
    
    private void BotonIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSecionActionPerformed
        // Recuperamos los datos del formulario
        String correo = txtCorreo.getText();
        char[] clave = TxtContraseña.getPassword();
        String contraseña = String.copyValueOf(clave);

        // Verificar si los campos están vacíos
        if (correo.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
            return;
        }

        // Verificamos si el campo correo es válido
        if (!ValidarEmail(correo)) {
            JOptionPane.showMessageDialog(null, "El correo electronico no puede estar vacío y debe ser válido.");
            return;
        }

        try {
            // Intentamos buscar un Usuario en la base de datos
            ArrayList<Usuario> usuariosBD = ConexionUsuarios.recuperarUsuariosDeBD();

            // Buscamos el usuario en el ArrayList
            Usuario usuarioEncontrado = null;
            for (Usuario usuario : usuariosBD) {
                if (usuario.getCorreo().equals(correo)) {
                    usuarioEncontrado = usuario;
                    break; // Salimos del bucle si encontramos al usuario
                }
            }

            // Comprobamos si el usuario está registrado
            if (usuarioEncontrado != null && usuarioEncontrado.getContraseña().equals(contraseña)) {
                JOptionPane.showMessageDialog(null, "¡Saludos, " + usuarioEncontrado.getNombre() + "!");

                // Asignar el usuario actual a la variable estática USUARIO
                USUARIO = usuarioEncontrado;

                // Puedes abrir la siguiente ventana aquí
                VentanaInicio ventana2 = new VentanaInicio();
                //                 ventana2.setExtendedState(VentanaInicio.MAXIMIZED_BOTH);
                ventana2.setVisible(true);
                ventana2.setLocationRelativeTo(null);
                this.dispose();

            } else {
                // Usuario no registrado o contraseña incorrecta
                JOptionPane.showMessageDialog(null, "ACCESO NEGADO. LOS DATOS INGRESADOS NO EXISTEN, POR FAVOR REGÍSTRESE");
                txtCorreo.setText("");
                TxtContraseña.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al recuperar usuarios: " + ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_BotonIniciarSecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciarSecion;
    private javax.swing.JButton BotonRegistrarce;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
