/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ConexionBD.ConexionHerramientas;
import Datos.Herramienta;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class VentanaInicio extends javax.swing.JFrame {

    LocalTime horaActual = LocalTime.now();
    public VentanaInicio() {
        initComponents();
        jLabel.setText("" + horaActual);
        txtDato.setText("<html>¡Bienvenido a nuestra tienda de tecnología!<br><br>"
            + "Nos alegra muchísimo tenerte aquí, " + Login.USUARIO.nombre + ".<br>"
            + "En nuestra tienda encontrarás una selección exclusiva de herramientas tecnológicas de última generación, <br>"
            + "desde computadoras y smartphones hasta componentes y accesorios, todo diseñado para optimizar tu trabajo.<br><br>"
            + "Sabemos lo importante que es para ti encontrar equipos confiables y de alto rendimiento, <br>"
            + "por eso nuestro equipo ha seleccionado cuidadosamente cada producto para garantizar <br>"
            + "que solo encuentres tecnología de primera calidad.<br><br>"
            + "Además, estamos aquí para acompañarte en cada paso: <br>"
            + "si necesitas asesoría técnica, recomendaciones de equipos o información sobre <br>"
            + "las últimas innovaciones, no dudes en consultarnos.<br><br>"
            + "¡Explora nuestras ofertas especiales, descuentos exclusivos y los últimos lanzamientos!<br>"
            + "Esperamos que encuentres exactamente lo que necesitas para tus proyectos.<br><br>"
            + "Gracias por elegirnos como tu proveedor de soluciones tecnológicas.<br><br>"
            + "¡Estamos aquí para impulsar tu productividad al máximo!</html>");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        txtDato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenuItem();
        Eliminarme = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ConsultarHerramienta = new javax.swing.JMenuItem();
        EditarHerramienta = new javax.swing.JMenuItem();
        EliminarHerramientas = new javax.swing.JMenuItem();
        RegistroHerramientas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("IR A VER LA LISTA DE HERRAMIENTAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("33");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 160, -1));

        txtDato.setBackground(new java.awt.Color(255, 255, 255));
        txtDato.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDato.setForeground(new java.awt.Color(255, 0, 0));
        txtDato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDato.setText("44");
        txtDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 37, 590, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Herramientas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        jMenu1.setText("Gestion Mi Cuenta ");

        Consultar.setText("Consultar mis datos...");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(Consultar);

        Editar.setText("Editar mis datos...");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jMenu1.add(Editar);

        Eliminarme.setText("Eliminarme...");
        Eliminarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarmeActionPerformed(evt);
            }
        });
        jMenu1.add(Eliminarme);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Gestion Herramientas");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        ConsultarHerramienta.setText("Consultar Herramienta....");
        ConsultarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarHerramientaActionPerformed(evt);
            }
        });
        jMenu3.add(ConsultarHerramienta);

        EditarHerramienta.setText("Editar datos de herramienta...");
        EditarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarHerramientaActionPerformed(evt);
            }
        });
        jMenu3.add(EditarHerramienta);

        EliminarHerramientas.setText("Eliminar herramienta...");
        EliminarHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarHerramientasActionPerformed(evt);
            }
        });
        jMenu3.add(EliminarHerramientas);

        RegistroHerramientas.setText("Registrar herramienta...");
        RegistroHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroHerramientasActionPerformed(evt);
            }
        });
        jMenu3.add(RegistroHerramientas);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Cerrar Secion");

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        MiCuenta consultar = new MiCuenta();
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        ConsultarActionPerformed(evt);
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarmeActionPerformed
        // TODO add your handling code here:
        ConsultarActionPerformed(evt);
    }//GEN-LAST:event_EliminarmeActionPerformed

    private void RegistroHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroHerramientasActionPerformed
        RegistroHerramientas consultar = new RegistroHerramientas();
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_RegistroHerramientasActionPerformed

    private void ConsultarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarHerramientaActionPerformed
         MiHerramienta consultar = new MiHerramienta();
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_ConsultarHerramientaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VentanaInicio.this.dispose();
        JOptionPane.showMessageDialog(null, "La sesión fue cerrada correctamente, gracias por entrar a nuestras instalaciones.");
        Login inicio = new Login();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true); 
        VentanaInicio.this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Crear una nueva ventana (JDialog)
            JDialog dialog = new JDialog();
            dialog.setTitle("Lista de Productos");
            dialog.setSize(600, 400);
            dialog.setLocationRelativeTo(null); // Centra la ventana
            dialog.setModal(true);

            // Crear el modelo de tabla
            DefaultTableModel model = new DefaultTableModel();

            // Agregar columnas
            model.addColumn("Código");
            model.addColumn("Nombre");
            model.addColumn("Precio");
            model.addColumn("Cantidad");

            // Obtener los productos de la base de datos
            ArrayList<Herramienta> herramienta = ConexionHerramientas.recuperarHerramientasDeBD();

            // Llenar la tabla con los datos
            for (Herramienta h : herramienta) {
                Object[] fila = new Object[]{
                    h.getCodigo(),
                    h.getNombre(),
                    h.getPrecio(),
                    h.getCantidad()  
                };
                model.addRow(fila);
            }

            // Crear la tabla y asignarle el modelo
            JTable tabla = new JTable(model);

            // Ajustar el ancho de las columnas
            tabla.getColumnModel().getColumn(0).setPreferredWidth(80);  // Código
            tabla.getColumnModel().getColumn(1).setPreferredWidth(200); // Nombre
            tabla.getColumnModel().getColumn(2).setPreferredWidth(100); // Precio
            tabla.getColumnModel().getColumn(3).setPreferredWidth(80);  // Cantidad

            // Crear un panel con scroll y agregar la tabla
            JScrollPane scrollPane = new JScrollPane(tabla);

            // Agregar el panel con scroll a la ventana
            dialog.add(scrollPane);

            // Mostrar la ventana
            dialog.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar los productos: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EditarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarHerramientaActionPerformed
        // TODO add your handling code here:
         MiCuenta consultar = new MiCuenta();
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_EditarHerramientaActionPerformed

    private void EliminarHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarHerramientasActionPerformed
        // TODO add your handling code here:
         MiCuenta consultar = new MiCuenta();
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_EliminarHerramientasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem ConsultarHerramienta;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem EditarHerramienta;
    private javax.swing.JMenuItem EliminarHerramientas;
    private javax.swing.JMenuItem Eliminarme;
    private javax.swing.JMenuItem RegistroHerramientas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDato;
    // End of variables declaration//GEN-END:variables
}
